# Generated by Django 5.2.6 on 2025-09-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('horas_trabalhadas', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em manutenção'), ('inoperante', 'Inoperante')], default='disponivel', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em manutenção'), ('inoperante', 'Inoperante')], default='disponivel', max_length=20)),
                ('odometro', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='viaturas/')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('pecas_usadas', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=100)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.equipamento')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.viatura')),
            ],
        ),
    ]
